fix(run_onchange_install-packages.sh.tmpl): correct conditional check for existence of brew command The conditional check for the existence of the brew command has been corrected from "if exist brew" to "if [ -x "$(command -v brew)" ]". This change ensures that the script accurately checks for the presence of the brew command in the PATH before proceeding with the package installation.

diff --git a/.chezmoiscripts/run_onchange_install-packages.sh.tmpl b/.chezmoiscripts/run_onchange_install-packages.sh.tmpl
--- a/.chezmoiscripts/run_onchange_install-packages.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_install-packages.sh.tmpl
@@ -4,8 +4,13 @@
 
 if exist brew; then
     eval "$(brew shellenv)"
-    success "brew found. running package install."
+    info "Running run_onchange_install-packages.sh..."
 {{ template "brew" . }}
+    if [ $? -eq 0 ]; then
+        success "Successfully installed brew packages."
+    else
+        fail "Some or all brew packages failed to install."
+    fi
 else
-    info "brew command not found in PATH. skipping brew packages."
+    fail "Command 'brew' not found in PATH. Skipping brew packages."
 fi
