feat(executable_git-update): add check for upstream branch before attempting pull and switch to main branch if available The script now includes a check to verify if an upstream branch is set before proceeding with the pull operation. If no upstream branch is set, the script will skip the pull process. Additionally, the script now attempts to switch to the main branch first and falls back to the master branch if the main branch does not exist. This enhancement ensures that the script operates smoothly and handles different branch scenarios effectively.

diff --git a/dot_local/bin/executable_git-update b/dot_local/bin/executable_git-update
--- a/dot_local/bin/executable_git-update
+++ b/dot_local/bin/executable_git-update
@@ -33,6 +33,24 @@ for directory in ~/gitwork/github/*/*; do
         cd "$directory" || { echo -e "${RED}Failed to change directory to $directory${NC}"; continue; }
         echo -e "${GREEN}Current directory: $(pwd)${NC}"
 
+        # Check if upstream branch is set
+        if ! git rev-parse --abbrev-ref --symbolic-full-name @{u} >/dev/null 2>&1; then
+            echo -e "${YELLOW}No upstream branch set. Skipping pull.${NC}"
+            echo
+            cd ~/gitwork/github/ || { echo -e "${RED}Failed to change directory back to ~/gitwork/github/${NC}"; exit 1; }
+            continue
+        fi
+
+        # Attempt to switch to main branch
+        git checkout main 2>/dev/null || { 
+            # If main branch doesn't exist, try switching to master
+            git checkout master || { 
+                echo -e "${RED}Failed to switch to the main or master branch.${NC}"; 
+                cd ~/gitwork/github/ || { echo -e "${RED}Failed to change directory back to ~/gitwork/github/${NC}"; exit 1; }
+                continue
+            }
+        }
+
         # Pull changes from git
         pull_changes
 
